# Site settings
title: Fruit Robot
email: iamkcerb@gmail.com
description: Fruit Robot is a site for learning about cross-platform Android / iOS development on RubyMotion.
baseurl: '/fruit-robot'
github_username: kcerb

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
