# Site settings
title: Fruit Robot
email: iamkcerb@gmail.com
description: A site for learning about cross-platform Android and iOS development on RubyMotion for beginners
baseurl: '/fruit-robot'
github_username: kcerb

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [with_toc_data]
