# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/android'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'first_app'
  app.api_version = '19'
  app.package = "com.kcerb.android.firstapp.programmatic"
  app.sub_activities = ['DisplayMessageActivity']
end
